name: PR checks

on:
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.x']

    steps:
      - name: Checkout the repository and the branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

      - name: Install the requirements
        run: pip install -r requirements.txt

      - name: Execute the unittests
        run: python3 -m unittest discover test

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - name: Checkout the repository and the branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

        - name: Install the requirements
          run: pip install -r requirements.txt

      - name: Execute the linting checks
        uses: reviewdog/action-flake8@v3.2.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          flake8_args: --config=.flake8

  coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - name: Checkout the repository and the branch
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          cache: 'pip'

        - name: Install the requirements
          run: pip install -r requirements.txt

        - name: Generate the coverage report
          run: pytest --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=app tests/ | tee pytest-coverage.txt

        - name: Execute the coverage checks
          uses: MishaKav/pytest-coverage-comment@v1.1.16
            with:
              github_token: ${{ secrets.GITHUB_TOKEN }}
              pytest-coverage-path: ./pytest-coverage.txt
              junitxml-path: ./pytest.xml
              hide-badge: true
              create-new-commit: true