name: Integrationtest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build . --file Dockerfile -t container-manager

      - name: Build the Docker image (Integrationtest)
        run: docker build . --file ./test/integrationtest/Dockerfile -t integrationtest

      - name: Create a local storage directory
        run: mkdir /tmp/storage && sudo chown 500:500 -R /tmp/storage

      - name: Run the integrationtest container
        run: |
          docker run -p 8080:8080 -v /tmp/storage:/storage -d integrationtest:latest && sleep 5
      - name: Test the integrationtest app
        run: |
          curl -I localhost:8080 2>/dev/null | head -n 1 | cut -d$' ' -f2 | grep 200