name: PR checks Test

on:
  pull_request:
    branches: [ main ]

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - name: Install SSH Client
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Install the requirements
        run: pip install -r requirements.txt && pip install pytest pytest-cov coverage-badge

      - uses: actions/checkout@v3

      - name: Generate documentation
        run: pydoc-markdown --render-toc && rm -rf docs/content && mv build/docs/* docs

      - name: Commit files
        if: steps.check_files.outputs.files_exists == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add --force docs
          git commit -m "Add coverage badge and documentation"
  
          - name: Push changes
            uses: ad-m/github-push-action@add-deploy-key-functionality
            with:
              repository: ${{ github.repository }}
              branch: ${{ github.ref }}
              force: true