name: PR checks Test

on:
  pull_request:
    branches: [ main ]

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      
      - name: Generate file
        run: rm docs/test1.txt && echo test3 > docs/test1.txt

      - name: "Check if file existence"
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "docs/test1.txt"
      
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs
          git commit -m "Test the action"

      - name: Push changes
        uses: ad-m/github-push-action@97a9d9f77011fcc1896dc07ea81353bfbc8e11d0
        with:
          pull_first: true
