name: PR checks Test

on:
  pull_request:
    branches: [ main ]

jobs:

  dummy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.x' ]

    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ref: test
          clean: true
          fetch-depth: 0
          
      
      - name: Commit files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git reset --soft HEAD~2
          git add .
          git commit -m "Test"
    
      - name: Push changes
        uses: ad-m/github-push-action@a3e0b8060c707698a058c22ed790ad59c8730b5e
        with:
          branch: ${{ github.head_ref }}
          force_with_lease: true
